export const tagTypes = {
  user: "user",
  auth: "auth",
  category: "category",
  sub_category: "sub_category",
  child_category: "child_category",
  filter: "filter",
  brand: "brand",
  specification: "specification",
  product: "product",
  banner: "banner",
  review: "review",
  question: "question",
  campaign: "campaign",
  offer: "offer",
  coupon: "coupon",
  wishlist: "wishlist",
  getme: "getme",
  order: "order",
  searchTerm: "searchTerm",
  site_setting: "site_setting",
};

export const tagTypesList = [
  tagTypes.user,
  tagTypes.auth,
  tagTypes.category,
  tagTypes.sub_category,
  tagTypes.child_category,
  tagTypes.filter,
  tagTypes.brand,
  tagTypes.specification,
  tagTypes.product,
  tagTypes.review,
  tagTypes.question,
  tagTypes.campaign,
  tagTypes.offer,
  tagTypes.coupon,
  tagTypes.pc_builder,
  tagTypes.wishlist,
  tagTypes.getme,
  tagTypes.order,
  tagTypes.searchTerm,
  tagTypes.site_setting,
];
