import Providers from "@/providers/Providers";
import { Abhaya_Libre, Manrope, Nunito } from "next/font/google";
import { Slide, ToastContainer } from "react-toastify";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-nunito",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-manrope",
});

const abhayaLibre = Abhaya_Libre({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-abhaya",
});

export const metadata = {
  title: "Grocery Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${manrope.variable} ${abhayaLibre.variable}`}
      >
        <Providers>
          {children}
          <ToastContainer
            position="bottom-right"
            autoClose={1500}
            transition={Slide}
            closeOnClick
          />
        </Providers>
      </body>
    </html>
  );
}
