import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nunito, Manrope, Abhaya_Libre } from 'next/font/google';


const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-nunito',
});

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-manrope',
});

const abhayaLibre = Abhaya_Libre({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-abhaya',
});


export const metadata = {
  title: "Grocery Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${nunito.variable} ${manrope.variable} ${abhayaLibre.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
